channels:
  - dharpa
  - conda-forge

host_requirements:
  - python
  - pip
  - hatchling
  - hatch-vcs

test:
  imports:
    - kiara_plugin.network_analysis
  source_files:
    - tests/
    - examples/
  commands:
    - kiara module list
